@ECHO OFF

SET OFFSET=500
SET JBOSS_SERVER_NAME=node_3A
IF "%UDP_ADDR%"=="" SET UDP_ADDR=239.30.1.1
SET /A NATIVE_ADMIN_PORT=5000 + %OFFSET% + 4
SET CURRENT_DIR=%~dp0
SET JBOSS_BASE_DIR=%CURRENT_DIR:~0,-1%
title %JBOSS_SERVER_NAME%

CALL ..\common.cmd

SET CMDLINE=%EAP_HOME%\bin\standalone.bat %ARGLINE%

IF NOT "%SET_ENV_ONLY%" == "true" ECHO %CMDLINE%
IF NOT "%SET_ENV_ONLY%" == "true" CALL %CMDLINE%

