package org.app.minibank.minibankref1.Arte;


/**
* org/app/minibank/minibankref1/Arte/ICalcPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/svn/Infrastructure/TestsAppli/EAP6Stdlib/EAP6StdlibPublic/src/main/idl/Calc.idl
* mercredi, 19. février 2014 09.01. h CET
*/

public class ICalcPOATie extends ICalcPOA
{

  // Constructors

  public ICalcPOATie ( org.app.minibank.minibankref1.Arte.ICalcOperations delegate ) {
      this._impl = delegate;
  }
  public ICalcPOATie ( org.app.minibank.minibankref1.Arte.ICalcOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public org.app.minibank.minibankref1.Arte.ICalcOperations _delegate() {
      return this._impl;
  }
  public void _delegate (org.app.minibank.minibankref1.Arte.ICalcOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void sayHello (String s)
  {
    _impl.sayHello(s);
  } // sayHello

  private org.app.minibank.minibankref1.Arte.ICalcOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class ICalcPOATie
