package org.app.minibank.minibankref1.Arte;


/**
* org/app/minibank/minibankref1/Arte/ICalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/svn/Infrastructure/TestsAppli/EAP6Stdlib/EAP6StdlibPublic/src/main/idl/Calc.idl
* mercredi, 19. février 2014 09.01. h CET
*/

public interface ICalcOperations 
{
  void sayHello (String s);
} // interface ICalcOperations
