package org.app.minibank.minibankref1.Arte;


/**
* org/app/minibank/minibankref1/Arte/ICalc_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/svn/Infrastructure/TestsAppli/EAP6Stdlib/EAP6StdlibPublic/src/main/idl/Calc.idl
* mercredi, 19. février 2014 09.01. h CET
*/

public class ICalc_Tie extends _ICalcImplBase
{

  // Constructors
  public ICalc_Tie ()
  {
  }

  public ICalc_Tie (org.app.minibank.minibankref1.Arte.ICalcOperations impl)
  {
    super ();
    _impl = impl;
  }

  public void sayHello (String s)
  {
    _impl.sayHello(s);
  } // sayHello

  private org.app.minibank.minibankref1.Arte.ICalcOperations _impl;

} // class ICalc_Tie
