package org.app.minibank.minibankref1.Arte;


/**
* org/app/minibank/minibankref1/Arte/ICalcPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/svn/Infrastructure/TestsAppli/EAP6Stdlib/EAP6StdlibPublic/src/main/idl/Calc.idl
* mercredi, 19. février 2014 09.01. h CET
*/

public abstract class ICalcPOA extends org.omg.PortableServer.Servant
 implements org.app.minibank.minibankref1.Arte.ICalcOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sayHello", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Arte/ICalc/sayHello
       {
         String s = in.read_string ();
         this.sayHello (s);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Arte/ICalc:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ICalc _this() 
  {
    return ICalcHelper.narrow(
    super._this_object());
  }

  public ICalc _this(org.omg.CORBA.ORB orb) 
  {
    return ICalcHelper.narrow(
    super._this_object(orb));
  }


} // class ICalcPOA
