package org.app.minibank.minibankref1.Arte;

/**
* org/app/minibank/minibankref1/Arte/ICalcHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/svn/Infrastructure/TestsAppli/EAP6Stdlib/EAP6StdlibPublic/src/main/idl/Calc.idl
* mercredi, 19. février 2014 09.01. h CET
*/

public final class ICalcHolder implements org.omg.CORBA.portable.Streamable
{
  public org.app.minibank.minibankref1.Arte.ICalc value = null;

  public ICalcHolder ()
  {
  }

  public ICalcHolder (org.app.minibank.minibankref1.Arte.ICalc initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.app.minibank.minibankref1.Arte.ICalcHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.app.minibank.minibankref1.Arte.ICalcHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.app.minibank.minibankref1.Arte.ICalcHelper.type ();
  }

}
