package org.app.minibank.minibankref1.Arte;


/**
* org/app/minibank/minibankref1/Arte/ICalc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/svn/Infrastructure/TestsAppli/EAP6Stdlib/EAP6StdlibPublic/src/main/idl/Calc.idl
* mercredi, 19. février 2014 09.01. h CET
*/

public interface ICalc extends ICalcOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
  public static final String DEFAULT_NS_PATH = "com/lodh/server/Arte/MinibankRef1/corba/ICalc";
} // interface ICalc
